package model.helpers.parsers;

import model.osm.OSMType;

import javax.xml.stream.XMLStreamReader;
import java.util.HashMap;

public class TypeParser {

    private static HashMap<String,OSMType> aerowayMap = new HashMap<>();
    private static HashMap<String,OSMType> amenityMap = new HashMap<>();
    private static HashMap<String,OSMType> barrierMap = new HashMap<>();
    private static HashMap<String,OSMType> boundaryMap = new HashMap<>();
    private static HashMap<String,OSMType> buildingMap = new HashMap<>();
    private static HashMap<String,OSMType> craftMap = new HashMap<>();
    private static HashMap<String,OSMType> highwayMap = new HashMap<>();
    private static HashMap<String,OSMType> historicMap = new HashMap<>();
    private static HashMap<String,OSMType> landuseMap = new HashMap<>();
    private static HashMap<String,OSMType> leisureMap = new HashMap<>();
    private static HashMap<String,OSMType> manMadeMap = new HashMap<>();
    private static HashMap<String,OSMType> militaryMap = new HashMap<>();
    private static HashMap<String,OSMType> naturalMap = new HashMap<>();
    private static HashMap<String,OSMType> placeMap = new HashMap<>();
    private static HashMap<String,OSMType> railwayMap = new HashMap<>();
    private static HashMap<String,OSMType> waterwayMap = new HashMap<>();

    public TypeParser() {
        fillMaps();
    }

    public OSMType setType(XMLStreamReader streamReader) {
        if(streamReader.getAttributeValue(0) == null) return null;
        String tag = streamReader.getAttributeValue(0).toLowerCase();
        switch (tag) {
            case "aeroway":     return aerowayMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "amenity":     return amenityMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "barrier":     return barrierMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "boundary":    return boundaryMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "building":    return buildingMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "craft":       return craftMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "highway":     return highwayMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "historic":    return historicMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "landuse":     return landuseMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "leisure":     return leisureMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "man_made":    return manMadeMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "military":    return militaryMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "natural":     return naturalMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "place":       return placeMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "railway":     return railwayMap.get(streamReader.getAttributeValue(1).toLowerCase());
            case "waterway":    return waterwayMap.get(streamReader.getAttributeValue(1).toLowerCase());
        }
        return null;
    }

    private void fillMaps(){
        fillAerowayMap();
        fillAmenityMap();
        fillBarrierMap();
        fillBoundaryMap();
        fillBuildingMap();
        fillCraftMap();
        fillHighwayMap();
        fillHistoricMap();
        fillLanduseMap();
        fillLeisureMap();
        fillManMadeMap();
        fillMilitaryMap();
        fillNaturalMap();
        fillPlaceMap();
        fillRailwayMap();
        fillWaterwayMap();
    }

    private void fillAerowayMap() {
        aerowayMap.put("aerodrome", OSMType.AERODROME);
        aerowayMap.put("apron", OSMType.APRON);
        aerowayMap.put("control_tower", OSMType.YES_BU);
        aerowayMap.put("hangar", OSMType.HANGAR_AE);
        aerowayMap.put("helipad", OSMType.HELIPAD);
        aerowayMap.put("marking", OSMType.MARKING);
        aerowayMap.put("parking_position", OSMType.PARKING_POSITION);
        aerowayMap.put("runway", OSMType.RUNWAY);
        aerowayMap.put("taxiway", OSMType.TAXIWAY);
        aerowayMap.put("terminal", OSMType.TERMINAL_AE);
    }

    private void fillAmenityMap() {
        amenityMap.put("administration", OSMType.ADMINISTRATION);
        amenityMap.put("ambulance_station", OSMType.AMBULANCE_STATION);
        amenityMap.put("animal_boarding", OSMType.ANIMAL_BOARDING);
        amenityMap.put("animal_breeding", OSMType.ANIMAL_BREEDING);
        amenityMap.put("animal_shelter", OSMType.ANIMAL_SHELTER);
        amenityMap.put("animal_training", OSMType.ANIMAL_TRAINING_AM);
        amenityMap.put("arts_centre", OSMType.ARTS_CENTRE);
        amenityMap.put("bank", OSMType.BANK_AM);
        amenityMap.put("bar", OSMType.BAR);
        amenityMap.put("bbq", OSMType.BBQ);
        amenityMap.put("bench", OSMType.BENCH);
        amenityMap.put("bicycle_parking", OSMType.BICYCLE_PARKING);
        amenityMap.put("bicycle_rental", OSMType.BICYCLE_RENTAL);
        amenityMap.put("bik", OSMType.BIK);
        amenityMap.put("bing", OSMType.BING);
        amenityMap.put("boat_storage",  OSMType.BOAT_STORAGE);
        amenityMap.put("brewery",  OSMType.BREWERY_AM);
        amenityMap.put("bus_station", OSMType.BUS_STATION);
        amenityMap.put("cabins", OSMType.CABINS);
        amenityMap.put("cafe", OSMType.CAFE);
        amenityMap.put("cafe;fast_food", OSMType.CAFE);
        amenityMap.put("canoe_hire", OSMType.CANOE_HIRE);
        amenityMap.put("car_rental", OSMType.CAR_RENTAL);
        amenityMap.put("car_sharing", OSMType.CAR_SHARING);
        amenityMap.put("car_wash", OSMType.CAR_WASH);
        amenityMap.put("charging_station", OSMType.CHARGING_STATION);
        amenityMap.put("childcare", OSMType.CHILDCARE);
        amenityMap.put("cinema", OSMType.CINEMA);
        amenityMap.put("clinic", OSMType.CLINIC);
        amenityMap.put("club", OSMType.CLUB);
        amenityMap.put("clubhouse", OSMType.CLUBHOUSE);
        amenityMap.put("coast_radar_station", OSMType.COAST_RADAR_STATION);
        amenityMap.put("college", OSMType.COLLEGE);
        amenityMap.put("community_centre", OSMType.COMMUNITY_CENTRE);
        amenityMap.put("community_centre;fast_food", OSMType.COMMUNITY_CENTRE);
        amenityMap.put("composting_site", OSMType.COMPOSTING_SITE);
        amenityMap.put("concert_hall", OSMType.CONCERT_HALL);
        amenityMap.put("conference_centre", OSMType.CONFERENCE_CENTRE);
        amenityMap.put("construction", OSMType.CONSTRUCTION_AM);
        amenityMap.put("courthouse", OSMType.COURTHOUSE);
        amenityMap.put("coworking_space", OSMType.COWORKING_SPACE);
        amenityMap.put("crematorium", OSMType.CREMATORIUM);
        amenityMap.put("crypt", OSMType.CRYPT);
        amenityMap.put("dancing_school", OSMType.DANCING_SCHOOL);
        amenityMap.put("daycare", OSMType.DAYCARE);
        amenityMap.put("dentist", OSMType.DENTIST);
        amenityMap.put("dive_centre", OSMType.DIVE_CENTRE);
        amenityMap.put("doctors", OSMType.DOCTORS);
        amenityMap.put("dog_training", OSMType.DOG_TRAINING);
        amenityMap.put("drinking_water", OSMType.DRINKING_WATER);
        amenityMap.put("driving_school", OSMType.DRIVING_SCHOOL);
        amenityMap.put("embassy", OSMType.EMBASSY);
        amenityMap.put("equestrian_field", OSMType.EQUESTRIAN_FIELD);
        amenityMap.put("events_venue", OSMType.EVENTS_VENUE);
        amenityMap.put("exhibition_centre", OSMType.EXHIBITION_CENTRE);
        amenityMap.put("fast_food", OSMType.FAST_FOOD);
        amenityMap.put("ferry_terminal", OSMType.FERRY_TERMINAL);
        amenityMap.put("festival_grounds", OSMType.FESTIVAL_GROUNDS);
        amenityMap.put("fire_station", OSMType.FIRE_STATION);
        amenityMap.put("flight_school", OSMType.FLIGHT_SCHOOL);
        amenityMap.put("fountain", OSMType.FOUNTAIN);
        amenityMap.put("fuel", OSMType.FUEL_AM);
        amenityMap.put("gambling", OSMType.GAMBLING);
        amenityMap.put("grave_yard", OSMType.GRAVE_YARD);
        amenityMap.put("hospice", OSMType.HOSPICE);
        amenityMap.put("hospital", OSMType.HOSPITAL_AM);
        amenityMap.put("ice_cream", OSMType.ICE_CREAM_AM);
        amenityMap.put("internet_cafe", OSMType.INTERNET_CAFE);
        amenityMap.put("jobcentre", OSMType.JOBCENTRE);
        amenityMap.put("kindergarten", OSMType.KINDERGARTEN_AM);
        amenityMap.put("library", OSMType.LIBRARY);
        amenityMap.put("marketplace", OSMType.MARKETPLACE);
        amenityMap.put("monastery", OSMType.MONASTERY_AM);
        amenityMap.put("mortuary", OSMType.MORTUARY);
        amenityMap.put("motorcycle_parking", OSMType.MOTORCYCLE_PARKING);
        amenityMap.put("music_school", OSMType.MUSIC_SCHOOL);
        amenityMap.put("music_venue", OSMType.MUSIC_VENUE);
        amenityMap.put("nightclub", OSMType.NIGHTCLUB);
        amenityMap.put("nursing_home", OSMType.NURSING_HOME);
        amenityMap.put("paring", OSMType.PARING);
        amenityMap.put("parking", OSMType.PARKING_AM);
        amenityMap.put("parking_entrance", OSMType.PARKING_ENTRANCE);
        amenityMap.put("parking_space", OSMType.PARKING_SPACE);
        amenityMap.put("parking_space_group", OSMType.PARKING_SPACE_GROUP);
        amenityMap.put("pavilion", OSMType.PAVILION_AM);
        amenityMap.put("pharmacy", OSMType.PHARMACY);
        amenityMap.put("place_of_worship", OSMType.PLACE_OF_WORSHIP);
        amenityMap.put("police", OSMType.POLICE);
        amenityMap.put("post_box", OSMType.POST_BOX);
        amenityMap.put("post_office", OSMType.POST_OFFICE);
        amenityMap.put("preschool", OSMType.PRESCHOOL);
        amenityMap.put("prison", OSMType.PRISON);
        amenityMap.put("pub", OSMType.PUB);
        amenityMap.put("public_bath", OSMType.PUBLIC_BATH);
        amenityMap.put("public_building", OSMType.PUBLIC_BUILDING);
        amenityMap.put("recycling", OSMType.RECYCLING);
        amenityMap.put("refugee_housing", OSMType.REFUGEE_HOUSING);
        amenityMap.put("rest_area", OSMType.REST_AREA_AM);
        amenityMap.put("restaurant", OSMType.RESTAURANT);
        amenityMap.put("restaurant;fast_food", OSMType.RESTAURANT);
        amenityMap.put("retirement_home", OSMType.RETIREMENT_HOME);
        amenityMap.put("riding_stables", OSMType.RIDING_STABLES);
        amenityMap.put("school", OSMType.SCHOOL_AM);
        amenityMap.put("science_park", OSMType.SCIENCE_PARK);
        amenityMap.put("scout_camp", OSMType.SCOUT_CAMP);
        amenityMap.put("scout_hut", OSMType.SCOUT_HUT);
        amenityMap.put("scrapyard", OSMType.SCRAPYARD);
        amenityMap.put("seats", OSMType.SEATS);
        amenityMap.put("shelter", OSMType.SHELTER);
        amenityMap.put("shop", OSMType.YES_BU);
        amenityMap.put("shower", OSMType.SHOWER);
        amenityMap.put("social_centre", OSMType.SOCIAL_CENTRE);
        amenityMap.put("social_facility", OSMType.SOCIAL_FACILITY);
        amenityMap.put("sport", OSMType.SPORT);
        amenityMap.put("square", OSMType.SQUARE_AM);
        amenityMap.put("student_accommodation", OSMType.STUDENT_ACCOMMODATION);
        amenityMap.put("studio", OSMType.STUDIO);
        amenityMap.put("swimming_pool", OSMType.SWIMMING_POOL);
        amenityMap.put("swingerclub", OSMType.SWINGERCLUB);
        amenityMap.put("taxi", OSMType.TAXI);
        amenityMap.put("theatre", OSMType.THEATRE);
        amenityMap.put("theatre;fast_food", OSMType.THEATRE);
        amenityMap.put("toilet", OSMType.TOILETS);
        amenityMap.put("toilets", OSMType.TOILETS);
        amenityMap.put("toilets;shower", OSMType.TOILETS);
        amenityMap.put("townhall", OSMType.TOWNHALL);
        amenityMap.put("training", OSMType.TRAINING);
        amenityMap.put("university", OSMType.UNIVERSITY_AM);
        amenityMap.put("vacuum_cleaner", OSMType.UNKNOWN);
        amenityMap.put("vehicle_inspection", OSMType.VEHICLE_INSPECTION);
        amenityMap.put("veterinary", OSMType.VETERINARY);
        amenityMap.put("waste_basket", OSMType.WASTE_BASKET);
        amenityMap.put("waste_disposal", OSMType.WASTE_DISPOSAL);
        amenityMap.put("waste_transfer_station", OSMType.WASTE_TRANSFER_STATION);
        amenityMap.put("weighbridge", OSMType.WEIGHBRIDGE);
    }

    private void fillBarrierMap() {
        barrierMap.put("block", OSMType.YES_BA);
        barrierMap.put("bollard", OSMType.YES_BA);
        barrierMap.put("bollard;fence", OSMType.YES_BA);
        barrierMap.put("boulders", OSMType.YES_BA);
        barrierMap.put("bulwark", OSMType.WALL);
        barrierMap.put("bus_trap", OSMType.UNKNOWN);
        barrierMap.put("cattle_grid", OSMType.UNKNOWN);
        barrierMap.put("chain", OSMType.YES_BA);
        barrierMap.put("city_wall", OSMType.WALL);
        barrierMap.put("construction", OSMType.UNKNOWN);
        barrierMap.put("curb", OSMType.UNKNOWN);
        barrierMap.put("ditch", OSMType.DITCH_BA);
        barrierMap.put("dyke", OSMType.UNKNOWN);
        barrierMap.put("earth_wall", OSMType.WALL);
        barrierMap.put("electric", OSMType.YES_BA);
        barrierMap.put("embankment", OSMType.EMBANKMENT_BA);
        barrierMap.put("entrance", OSMType.UNKNOWN);
        barrierMap.put("fec", OSMType.UNKNOWN);
        barrierMap.put("fence", OSMType.FENCE);
        barrierMap.put("gate", OSMType.UNKNOWN);
        barrierMap.put("ged", OSMType.UNKNOWN);
        barrierMap.put("guard_rail", OSMType.GUARD_RAIL);
        barrierMap.put("handrail", OSMType.YES_BA);
        barrierMap.put("hedge", OSMType.HEDGE);
        barrierMap.put("hedge_bank", OSMType.HEDGE);
        barrierMap.put("hegde", OSMType.HEDGE);
        barrierMap.put("jersey_barrier", OSMType.YES_BA);
        barrierMap.put("kerb", OSMType.KERB);
        barrierMap.put("lift_gate", OSMType.UNKNOWN);
        barrierMap.put("log", OSMType.UNKNOWN);
        barrierMap.put("natural", OSMType.YES_BA);
        barrierMap.put("no", OSMType.UNKNOWN);
        barrierMap.put("noise_barrier", OSMType.YES_BA);
        barrierMap.put("railing", OSMType.UNKNOWN);
        barrierMap.put("retaining_wall", OSMType.RETAINING_WALL);
        barrierMap.put("rocks", OSMType.YES_BA);
        barrierMap.put("rope", OSMType.UNKNOWN);
        barrierMap.put("sally_port", OSMType.UNKNOWN);
        barrierMap.put("stone", OSMType.YES_BA);
        barrierMap.put("stones", OSMType.YES_BA);
        barrierMap.put("swing_gate", OSMType.UNKNOWN);
        barrierMap.put("tank_trap", OSMType.UNKNOWN);
        barrierMap.put("toll_booth", OSMType.YES_BU);
        barrierMap.put("wall", OSMType.WALL);
        barrierMap.put("wire_fence", OSMType.YES_BA);
        barrierMap.put("wooden_poles", OSMType.YES_BA);
        barrierMap.put("yes", OSMType.YES_BA);
    }

    private void fillBoundaryMap() {
        boundaryMap.put("administrative", OSMType.ADMINISTRATIVE);
        boundaryMap.put("maritime", OSMType.UNKNOWN);
        boundaryMap.put("national_park", OSMType.UNKNOWN);
        boundaryMap.put("parcel_front", OSMType.UNKNOWN);
        boundaryMap.put("political", OSMType.UNKNOWN);
        boundaryMap.put("postal_code", OSMType.UNKNOWN);
        boundaryMap.put("protected_area", OSMType.PROTECTED_AREA);
    }

    private void fillBuildingMap() {
        buildingMap.put("abandoned", OSMType.YES_BU);
        buildingMap.put("allotment_house", OSMType.YES_BU);
        buildingMap.put("apartments", OSMType.APARTMENTS);
        buildingMap.put("bank",  OSMType.YES_BU);
        buildingMap.put("barn", OSMType.YES_BU);
        buildingMap.put("bicycle_parking", OSMType.YES_BU);
        buildingMap.put("biograf_og_restaurant", OSMType.YES_BU);
        buildingMap.put("boat", OSMType.BOAT);
        buildingMap.put("boathouse", OSMType.YES_BU);
        buildingMap.put("brewery", OSMType.YES_BU);
        buildingMap.put("bridge", OSMType.YES_BU);
        buildingMap.put("bungalow", OSMType.HOUSE);
        buildingMap.put("bunker", OSMType.BUNKER_BU);
        buildingMap.put("cabin", OSMType.CABIN);
        buildingMap.put("canteen", OSMType.YES_BU);
        buildingMap.put("carport", OSMType.UNKNOWN);
        buildingMap.put("castle",  OSMType.CASTLE_BU);
        buildingMap.put("cathedral", OSMType.YES_BU);
        buildingMap.put("chalet", OSMType.HOUSE);
        buildingMap.put("chapel", OSMType.YES_BU);
        buildingMap.put("chimney", OSMType.TOWER);
        buildingMap.put("church", OSMType.CHURCH_BU);
        buildingMap.put("church_tower", OSMType.TOWER);
        buildingMap.put("cinema", OSMType.YES_BU);
        buildingMap.put("civic", OSMType.YES_BU);
        buildingMap.put("cold_store", OSMType.YES_BU);
        buildingMap.put("collapsed", OSMType.YES_BU);
        buildingMap.put("college", OSMType.COLLEGE_BU);
        buildingMap.put("commercial", OSMType.COMMERCIAL_BU);
        buildingMap.put("construction", OSMType.CONSTRUCTION_BU);
        buildingMap.put("container", OSMType.UNKNOWN);
        buildingMap.put("cottage", OSMType.HOUSE);
        buildingMap.put("court_house", OSMType.YES_BU);
        buildingMap.put("cowshed", OSMType.YES_BU);
        buildingMap.put("data_center", OSMType.YES_BU);
        buildingMap.put("detached", OSMType.DETACHED);
        buildingMap.put("disused", OSMType.YES_BU);
        buildingMap.put("dormitory", OSMType.DORMITORY);
        buildingMap.put("electricity", OSMType.YES_BU);
        buildingMap.put("factory", OSMType.YES_BU);
        buildingMap.put("farm", OSMType.FARM_BU);
        buildingMap.put("farm_auxiliary", OSMType.FARM_AUXILIARY);
        buildingMap.put("fire_station", OSMType.YES_BU);
        buildingMap.put("fortress", OSMType.YES_BU);
        buildingMap.put("garage", OSMType.YES_BU);
        buildingMap.put("garages", OSMType.YES_BU);
        buildingMap.put("gazebo", OSMType.YES_BU);
        buildingMap.put("grandstand", OSMType.OPEN_AIR);
        buildingMap.put("greenhouse", OSMType.GREENHOUSE);
        buildingMap.put("ground_station", OSMType.STATION);
        buildingMap.put("guy_wire_anchor", OSMType.UNKNOWN);
        buildingMap.put("hall", OSMType.YES_BU);
        buildingMap.put("hangar", OSMType.YES_BU);
        buildingMap.put("hiu", OSMType.YES_BU);
        buildingMap.put("hom", OSMType.YES_BU);
        buildingMap.put("home", OSMType.YES_BU);
        buildingMap.put("hoo", OSMType.YES_BU);
        buildingMap.put("hospital", OSMType.HOSPITAL_BU);
        buildingMap.put("hostel", OSMType.YES_BU);
        buildingMap.put("hotel", OSMType.YES_BU);
        buildingMap.put("house", OSMType.HOUSE);
        buildingMap.put("house;garage", OSMType.HOUSE);
        buildingMap.put("house;garage;barn", OSMType.HOUSE);
        buildingMap.put("houseboat", OSMType.BOAT);
        buildingMap.put("hut", OSMType.HUT);
        buildingMap.put("industrial", OSMType.INDUSTRIAL_BU);
        buildingMap.put("industrial;yes", OSMType.INDUSTRIAL_BU);
        buildingMap.put("kindergarten", OSMType.KINDERGARTEN_BU);
        buildingMap.put("kiosk", OSMType.YES_BU);
        buildingMap.put("library", OSMType.YES_BU);
        buildingMap.put("maill", OSMType.YES_BU);
        buildingMap.put("mall", OSMType.YES_BU);
        buildingMap.put("manor",  OSMType.MANOR_BU);
        buildingMap.put("mansion",  OSMType.MANOR_BU);
        buildingMap.put("manufacture",  OSMType.YES_BU);
        buildingMap.put("mink_feed_tank",  OSMType.TANK);
        buildingMap.put("mink_shed",  OSMType.YES_BU);
        buildingMap.put("monastery",  OSMType.YES_BU);
        buildingMap.put("mosque", OSMType.YES_BU);
        buildingMap.put("museum", OSMType.YES_BU);
        buildingMap.put("observatory", OSMType.YES_BU);
        buildingMap.put("office", OSMType.OFFICE_BU);
        buildingMap.put("open_air", OSMType.OPEN_AIR);
        buildingMap.put("outbuilding", OSMType.YES_BU);
        buildingMap.put("outhouse", OSMType.YES_BU);
        buildingMap.put("pagoda", OSMType.OPEN_AIR);
        buildingMap.put("palace", OSMType.YES_BU);
        buildingMap.put("parking", OSMType.PARKING_BU);
        buildingMap.put("pavilion", OSMType.YES_BU);
        buildingMap.put("pillar", OSMType.UNKNOWN);
        buildingMap.put("platform", OSMType.PLATFORM);
        buildingMap.put("playground", OSMType.PLAYGROUND);
        buildingMap.put("playhouse", OSMType.YES_BU);
        buildingMap.put("porch", OSMType.UNKNOWN);
        buildingMap.put("primary", OSMType.YES_BU);
        buildingMap.put("prison", OSMType.YES_BU);
        buildingMap.put("private", OSMType.YES_BU);
        buildingMap.put("production_hall", OSMType.YES_BU);
        buildingMap.put("public", OSMType.PUBLIC);
        buildingMap.put("pumping_station", OSMType.YES_BU);
        buildingMap.put("q", OSMType.YES_BU);
        buildingMap.put("recreational", OSMType.YES_BU);
        buildingMap.put("residential", OSMType.RESIDENTIAL_BU);
        buildingMap.put("restaurant", OSMType.YES_BU);
        buildingMap.put("retail", OSMType.RETAIL_BU);
        buildingMap.put("rescue station", OSMType.YES_BU);
        buildingMap.put("riding_hall", OSMType.YES_BU);
        buildingMap.put("river", OSMType.RIVER);
        buildingMap.put("road", OSMType.ROAD);
        buildingMap.put("roof", OSMType.ROOF);
        buildingMap.put("ruin", OSMType.YES_BU);
        buildingMap.put("ruins", OSMType.YES_BU);
        buildingMap.put("sandholmgård", OSMType.MANOR_BU);
        buildingMap.put("school", OSMType.SCHOOL_BU);
        buildingMap.put("semidetached_house", OSMType.HOUSE);
        buildingMap.put("service", OSMType.YES_BU);
        buildingMap.put("shed", OSMType.SHED);
        buildingMap.put("shelter", OSMType.OPEN_AIR);
        buildingMap.put("ship", OSMType.BOAT);
        buildingMap.put("shool", OSMType.SCHOOL_BU);
        buildingMap.put("shop", OSMType.YES_BU);
        buildingMap.put("silo", OSMType.SILO_BU);
        buildingMap.put("skur", OSMType.SHED);
        buildingMap.put("slurry_tank", OSMType.TANK);
        buildingMap.put("slurry__tank", OSMType.TANK);
        buildingMap.put("so", OSMType.YES_BU);
        buildingMap.put("sports", OSMType.YES_BU);
        buildingMap.put("sports_hall", OSMType.YES_BU);
        buildingMap.put("stable", OSMType.STABLE);
        buildingMap.put("stadium", OSMType.YES_BU);
        buildingMap.put("stald", OSMType.STABLE);
        buildingMap.put("stands", OSMType.UNKNOWN);
        buildingMap.put("static_caravan", OSMType.UNKNOWN);
        buildingMap.put("station", OSMType.STATION);
        buildingMap.put("storage", OSMType.YES_BU);
        buildingMap.put("storage_tank", OSMType.TANK);
        buildingMap.put("sty", OSMType.UNKNOWN);
        buildingMap.put("substation", OSMType.YES_BU);
        buildingMap.put("supermarket", OSMType.SUPERMARKET);
        buildingMap.put("synagogue", OSMType.YES_BU);
        buildingMap.put("tank", OSMType.TANK);
        buildingMap.put("tech_cab", OSMType.UNKNOWN);
        buildingMap.put("temple", OSMType.YES_BU);
        buildingMap.put("tent", OSMType.UNKNOWN);
        buildingMap.put("terrace", OSMType.UNKNOWN);
        buildingMap.put("theatre", OSMType.THEATRE);
        buildingMap.put("tipi", OSMType.UNKNOWN);
        buildingMap.put("toilets", OSMType.YES_BU);
        buildingMap.put("tower", OSMType.TOWER);
        buildingMap.put("trade", OSMType.UNKNOWN);
        buildingMap.put("train_station", OSMType.STATION);
        buildingMap.put("transformer_tower", OSMType.YES_BU);
        buildingMap.put("transportation", OSMType.YES_BU);
        buildingMap.put("ty", OSMType.YES_BU);
        buildingMap.put("udehus", OSMType.YES_BU);
        buildingMap.put("university", OSMType.UNIVERSITY_BU);
        buildingMap.put("various", OSMType.YES_BU);
        buildingMap.put("warehouse", OSMType.WAREHOUSE);
        buildingMap.put("wastewater_plant", OSMType.YES_BU);
        buildingMap.put("watertower", OSMType.TOWER);
        buildingMap.put("water_tower", OSMType.TOWER);
        buildingMap.put("windmill",  OSMType.YES_BU);
        buildingMap.put("lifeguard", OSMType.UNKNOWN);
        buildingMap.put("yes", OSMType.YES_BU);
        buildingMap.put("yu", OSMType.YES_BU);
        buildingMap.put("7y", OSMType.YES_BU);
    }

    private void fillCraftMap() {
        craftMap.put("arborist", OSMType.ARBORIST);
        craftMap.put("beekeeper", OSMType.BEEKEEPER);
        craftMap.put("blacksmith", OSMType.BLACKSMITH);
        craftMap.put("boatbuilder", OSMType.BOATBUILDER);
        craftMap.put("brewery", OSMType.BREWERY_CR);
        craftMap.put("brush maker", OSMType.BRUSH_MAKER);
        craftMap.put("brushmaker", OSMType.BRUSH_MAKER);
        craftMap.put("builder", OSMType.BUILDER);
        craftMap.put("carpenter", OSMType.CARPENTER);
        craftMap.put("caterer", OSMType.CATERER);
        craftMap.put("catering", OSMType.CATERING);
        craftMap.put("clockmaker", OSMType.CLOCKMAKER);
        craftMap.put("confectionery", OSMType.CONFECTIONERY_CR);
        craftMap.put("dairy", OSMType.DAIRY);
        craftMap.put("electrician", OSMType.ELECTRICIAN);
        craftMap.put("electronics_repair", OSMType.ELECTRONICS_REPAIR);
        craftMap.put("gardener", OSMType.GARDENER);
        craftMap.put("handicraft", OSMType.HANDICRAFT);
        craftMap.put("hvac", OSMType.HVAC);
        craftMap.put("jeweller", OSMType.JEWELLER);
        craftMap.put("locksmith", OSMType.LOCKSMITH_CR);
        craftMap.put("mason", OSMType.LOCKSMITH_CR);
        craftMap.put("metal_construction", OSMType.METAL_CONSTRUCTION);
        craftMap.put("photographer", OSMType.PHOTOGRAPHER);
        craftMap.put("plumber", OSMType.PLUMBER);
        craftMap.put("pottery", OSMType.POTTERY);
        craftMap.put("printing", OSMType.PRINTING);
        craftMap.put("roofer", OSMType.ROOFER);
        craftMap.put("sawmill", OSMType.SAWMILL);
        craftMap.put("sculptor", OSMType.SCULPTOR);
        craftMap.put("stonemason", OSMType.STONEMASON);
    }

    private void fillHighwayMap() {
        highwayMap.put("a3.0", OSMType.TERTIARY);
        highwayMap.put("abandoned", OSMType.UNKNOWN);
        highwayMap.put("bridleway", OSMType.BRIDLEWAY);
        highwayMap.put("bus_guideway", OSMType.ROAD);
        highwayMap.put("bus_stop", OSMType.UNKNOWN);
        highwayMap.put("construction", OSMType.UNKNOWN);
        highwayMap.put("corridor", OSMType.ROAD);
        highwayMap.put("crossing", OSMType.ROAD);
        highwayMap.put("cycleway", OSMType.CYCLEWAY_HIG);
        highwayMap.put("driveway", OSMType.ROAD);
        highwayMap.put("elevator", OSMType.YES_BU);
        highwayMap.put("fence", OSMType.FENCE);
        highwayMap.put("footway", OSMType.FOOTWAY);
        highwayMap.put("living_street", OSMType.LIVING_STREET);
        highwayMap.put("motorway", OSMType.MOTORWAY);
        highwayMap.put("motorway_link", OSMType.MOTORWAY);
        highwayMap.put("path", OSMType.PATH);
        highwayMap.put("pedestrian", OSMType.PEDESTRIAN);
        highwayMap.put("permissive", OSMType.ROAD);
        highwayMap.put("platform", OSMType.PLATFORM);
        highwayMap.put("primary", OSMType.PRIMARY);
        highwayMap.put("primary_link", OSMType.PRIMARY);
        highwayMap.put("proposed", OSMType.UNKNOWN);
        highwayMap.put("raceway", OSMType.RACEWAY);
        highwayMap.put("razed", OSMType.UNKNOWN);
        highwayMap.put("residential", OSMType.RESIDENTIAL_HIG);
        highwayMap.put("rest_area", OSMType.ROAD);
        highwayMap.put("road", OSMType.ROAD);
        highwayMap.put("secondary", OSMType.SECONDARY);
        highwayMap.put("secondary_link", OSMType.SECONDARY);
        highwayMap.put("service", OSMType.SERVICE_HIG);
        highwayMap.put("services", OSMType.SERVICE_HIG);
        highwayMap.put("steps", OSMType.STEPS);
        highwayMap.put("tertiary", OSMType.TERTIARY);
        highwayMap.put("tertiary_link", OSMType.TERTIARY);
        highwayMap.put("track", OSMType.TRACK_HIG);
        highwayMap.put("trunk", OSMType.TRUNK);
        highwayMap.put("trunk_link", OSMType.TRUNK_LINK);
        highwayMap.put("unclassified", OSMType.ROAD);
    }

    private void fillHistoricMap() {
        historicMap.put("archaeological_site", OSMType.ARCHAEOLOGICAL_SITE);
        historicMap.put("bank", OSMType.YES_BU);
        historicMap.put("battlefield", OSMType.YES_HI);
        historicMap.put("building", OSMType.HOUSE);
        historicMap.put("bunker", OSMType.BUNKER_BU);
        historicMap.put("castle", OSMType.CASTLE_BU);
        historicMap.put("cathedral", OSMType.YES_BU);
        historicMap.put("church", OSMType.CHURCH_BU);
        historicMap.put("city_gate", OSMType.UNKNOWN);
        historicMap.put("city_hall", OSMType.YES_BU);
        historicMap.put("coastal_artillery", OSMType.UNKNOWN);
        historicMap.put("construction", OSMType.CONSTRUCTION_BU);
        historicMap.put("det gamle sømandshjem", OSMType.HOUSE);
        historicMap.put("elkjærhøj voldsted", OSMType.WALL);
        historicMap.put("farm", OSMType.FARM_BU);
        historicMap.put("fire_station", OSMType.FIRE_STATION);
        historicMap.put("fort", OSMType.YES_BU);
        historicMap.put("grave", OSMType.GRAVE);
        historicMap.put("heritage", OSMType.HERITAGE);
        historicMap.put("hospital", OSMType.HOSPITAL_BU);
        historicMap.put("house", OSMType.HOUSE);
        historicMap.put("industrial", OSMType.INDUSTRIAL_BU);
        historicMap.put("manor", OSMType.MANOR_BU);
        historicMap.put("memorial", OSMType.MEMORIAL);
        historicMap.put("monastery", OSMType.YES_BU);
        historicMap.put("monument", OSMType.MONUMENT);
        historicMap.put("no", OSMType.UNKNOWN);
        historicMap.put("palace", OSMType.YES_BU);
        historicMap.put("prison", OSMType.PRISON);
        historicMap.put("premier is", OSMType.UNKNOWN);
        historicMap.put("railway", OSMType.RAIL);
        historicMap.put("school;post_office", OSMType.SCHOOL_BU);
        historicMap.put("ruins", OSMType.YES_BU);
        historicMap.put("ship", OSMType.BOAT);
        historicMap.put("studio", OSMType.YES_BU);
        historicMap.put("tomb", OSMType.TOMB);
        historicMap.put("townhall", OSMType.TOWNHALL);
        historicMap.put("wall", OSMType.WALL);
        historicMap.put("yes", OSMType.YES_HI);
    }

    private void fillLanduseMap() {
        landuseMap.put("allotments", OSMType.ALLOTMENTS_LA);
        landuseMap.put("animal_keeping",  OSMType.ANIMAL_KEEPING);
        landuseMap.put("apiary",  OSMType.UNKNOWN);
        landuseMap.put("aquaculture",  OSMType.AQUACULTURE);
        landuseMap.put("artproject",  OSMType.UNKNOWN);
        landuseMap.put("basin", OSMType.BASIN);
        landuseMap.put("brownfield", OSMType.BROWNFIELD);
        landuseMap.put("cemetery", OSMType.CEMETERY);
        landuseMap.put("coal_storage", OSMType.COAL_STORAGE);
        landuseMap.put("commercial", OSMType.COMMERCIAL_LA);
        landuseMap.put("conservation", OSMType.CONSERVATION);
        landuseMap.put("construction", OSMType.CONSTRUCTION_LA);
        landuseMap.put("courtyard", OSMType.COURTYARD);
        landuseMap.put("depot", OSMType.DEPOT);
        landuseMap.put("dune", OSMType.DUNE);
        landuseMap.put("farmland", OSMType.FARMLAND);
        landuseMap.put("farmland;greenfield", OSMType.FARMLAND);
        landuseMap.put("farmyard", OSMType.FARMYARD);
        landuseMap.put("ferry_terminal", OSMType.FERRY_TERMINAL_LA);
        landuseMap.put("festival_grounds", OSMType.FESTIVAL_GROUNDS);
        landuseMap.put("fishfarm", OSMType.FISHFARM);
        landuseMap.put("flade_hede", OSMType.HEATH_LA);
        landuseMap.put("forest", OSMType.FOREST);
        landuseMap.put("garages", OSMType.YES_BU);
        landuseMap.put("garden", OSMType.GARDEN_LA);
        landuseMap.put("grass", OSMType.GRASS);
        landuseMap.put("grasss", OSMType.GRASS);
        landuseMap.put("grassland", OSMType.GRASSLAND_LA);
        landuseMap.put("green", OSMType.GREEN);
        landuseMap.put("greenfield", OSMType.GREENFIELD);
        landuseMap.put("greenhouse", OSMType.GREENHOUSE_LA);
        landuseMap.put("greenhouse_horticulture", OSMType.GREENHOUSE_HORTICULTURE);
        landuseMap.put("harbour", OSMType.HARBOUR);
        landuseMap.put("heath", OSMType.HEATH_LA);
        landuseMap.put("hedge", OSMType.HEDGE);
        landuseMap.put("industrial", OSMType.INDUSTRIAL_LA);
        landuseMap.put("landfill", OSMType.LANDFILL);
        landuseMap.put("meadow", OSMType.MEADOW);
        landuseMap.put("military", OSMType.MILITARY_LA);
        landuseMap.put("orchard", OSMType.ORCHARD);
        landuseMap.put("park", OSMType.PARK);
        landuseMap.put("pasture", OSMType.PASTURE);
        landuseMap.put("plantation", OSMType.YES_BU);
        landuseMap.put("plant_nursery", OSMType.PLANT_NURSERY);
        landuseMap.put("pond", OSMType.POND_WA);
        landuseMap.put("quarry", OSMType.QUARRY);
        landuseMap.put("raceway", OSMType.RACEWAY);
        landuseMap.put("railway", OSMType.RAILWAY_LA);
        landuseMap.put("recreation_ground", OSMType.RECREATION_GROUND_LA);
        landuseMap.put("religious", OSMType.RELIGIOUS_LA);
        landuseMap.put("reservoir", OSMType.RESERVOIR);
        landuseMap.put("residential", OSMType.RESIDENTIAL_LA);
        landuseMap.put("retail", OSMType.RETAIL_LA);
        landuseMap.put("sand", OSMType.SAND);
        landuseMap.put("schoolyard", OSMType.SCHOOLYARD_LA);
        landuseMap.put("scout_camp", OSMType.SCOUT_CAMP);
        landuseMap.put("scrub", OSMType.SCRUB);
        landuseMap.put("shipyard", OSMType.SHIPYARD);
        landuseMap.put("tee", OSMType.TREE);
        landuseMap.put("track", OSMType.TRACK_HIG);
        landuseMap.put("traffic_island", OSMType.TRAFFIC_ISLAND);
        landuseMap.put("tree", OSMType.TREE);
        landuseMap.put("village_green", OSMType.VILLAGE_GREEN);
        landuseMap.put("vineyard", OSMType.VINEYARD);
        landuseMap.put("wood", OSMType.WOOD);
        landuseMap.put("workyard", OSMType.WORKYARD);
        landuseMap.put("yes", OSMType.YES_LA);
    }

    private void fillLeisureMap(){
        leisureMap.put("amusement_arcade", OSMType.AMUSEMENT_ARCADE);
        leisureMap.put("animal_training", OSMType.ANIMAL_TRAINING_LE);
        leisureMap.put("bandstand", OSMType.BANDSTAND);
        leisureMap.put("beach", OSMType.BEACH_LE);
        leisureMap.put("bird_hide", OSMType.BIRD_HIDE);
        leisureMap.put("bowling_alley", OSMType.BOWLING_ALLEY);
        leisureMap.put("bownling_alley", OSMType.BOWLING_ALLEY);
        leisureMap.put("building", OSMType.YES_BU);
        leisureMap.put("club", OSMType.CLUB_LE);
        leisureMap.put("common", OSMType.COMMON);
        leisureMap.put("dance", OSMType.DANCE);
        leisureMap.put("disc_golf_course", OSMType.DISC_GOLF_COURSE);
        leisureMap.put("dog_park", OSMType.DOG_PARK);
        leisureMap.put("equestrian", OSMType.EQUESTRIAN);
        leisureMap.put("fairground", OSMType.FAIRGROUND);
        leisureMap.put("firepit", OSMType.UNKNOWN);
        leisureMap.put("fish", OSMType.FISHING_LE);
        leisureMap.put("fishing", OSMType.FISHING_LE);
        leisureMap.put("fitness_centre",  OSMType.FITNESS_CENTRE);
        leisureMap.put("fitness_station",  OSMType.FITNESS_STATION);
        leisureMap.put("garden",  OSMType.GARDEN);
        leisureMap.put("golf_course",  OSMType.GOLF_COURSE);
        leisureMap.put("hackerspace", OSMType.HACKERSPACE);
        leisureMap.put("horse_riding", OSMType.HORSE_RIDING);
        leisureMap.put("ice_rink", OSMType.ICE_RINK);
        leisureMap.put("marina", OSMType.MARINA);
        leisureMap.put("maze", OSMType.MAZE);
        leisureMap.put("miniature_golf", OSMType.MINIATURE_GOLF);
        leisureMap.put("mini_soccer", OSMType.MINI_SOCCER);
        leisureMap.put("nature_reserve", OSMType.NATURE_RESERVE);
        leisureMap.put("outdoor_seating", OSMType.OUTDOOR_SEATING);
        leisureMap.put("paintball", OSMType.PAINTBALL);
        leisureMap.put("park", OSMType.PARK);
        leisureMap.put("petanque", OSMType.PETANQUE);
        leisureMap.put("picnic_area", OSMType.PICNIC_AREA);
        leisureMap.put("picnic_table", OSMType.UNKNOWN);
        leisureMap.put("picnic_site", OSMType.PICNIC_AREA);
        leisureMap.put("pitch", OSMType.PITCH);
        leisureMap.put("playground", OSMType.PLAYGROUND);
        leisureMap.put("play ground", OSMType.PLAYGROUND);
        leisureMap.put("playground=slide", OSMType.PLAYGROUND);
        leisureMap.put("pool", OSMType.POOL);
        leisureMap.put("racetrack", OSMType.RACETRACK);
        leisureMap.put("recreation_ground",  OSMType.RECREATION_GROUND_LE);
        leisureMap.put("sauna",  OSMType.YES_BU);
        leisureMap.put("schoolyard",  OSMType.SCHOOLYARD);
        leisureMap.put("scout",  OSMType.SCOUT);
        leisureMap.put("scouts",  OSMType.SCOUT);
        leisureMap.put("shooting_ground",  OSMType.SHOOTING_GROUND);
        leisureMap.put("slipway", OSMType.SLIPWAY);
        leisureMap.put("soccer", OSMType.SOCCER);
        leisureMap.put("soccergolf", OSMType.SOCCER_GOLF);
        leisureMap.put("soccer_golf", OSMType.SOCCER_GOLF);
        leisureMap.put("social_club", OSMType.SOCIAL_CLUB);
        leisureMap.put("sports_centre", OSMType.SPORTS_CENTRE);
        leisureMap.put("stadium", OSMType.STADIUM_LE);
        leisureMap.put("stage", OSMType.STAGE);
        leisureMap.put("summer_camp", OSMType.SUMMER_CAMP);
        leisureMap.put("swimming", OSMType.SWIMMING_AREA);
        leisureMap.put("swimming_area", OSMType.SWIMMING_AREA);
        leisureMap.put("swimming_pool", OSMType.SWIMMING_POOL_LE);
        leisureMap.put("theme_park", OSMType.PARK);
        leisureMap.put("track", OSMType.TRACK_LE);
        leisureMap.put("trampoline_park", OSMType.PARK);
        leisureMap.put("water_park", OSMType.PARK);
        leisureMap.put("wildlife_hide", OSMType.WILDLIFE_HIDE);
        leisureMap.put("yes", OSMType.YES_LE);
    }

    private void fillManMadeMap() {
        manMadeMap.put("advertising", OSMType.UNKNOWN);
        manMadeMap.put("antenna", OSMType.UNKNOWN);
        manMadeMap.put("artproject", OSMType.UNKNOWN);
        manMadeMap.put("bell_tower", OSMType.TOWER);
        manMadeMap.put("breakwater", OSMType.BREAKWATER);
        manMadeMap.put("bridge", OSMType.BRIDGE_MA);
        manMadeMap.put("bunker", OSMType.BUNKER_BU);
        manMadeMap.put("bunker_silo", OSMType.BUNKER_SILO);
        manMadeMap.put("building", OSMType.YES_BU);
        manMadeMap.put("campanile", OSMType.TOWER);
        manMadeMap.put("cellar_entrance", OSMType.UNKNOWN);
        manMadeMap.put("chimney", OSMType.TOWER);
        manMadeMap.put("clearcut", OSMType.CLEARCUT);
        manMadeMap.put("communications_dish", OSMType.UNKNOWN);
        manMadeMap.put("communications_tower", OSMType.TOWER);
        manMadeMap.put("courtyard", OSMType.COURTYARD);
        manMadeMap.put("crane", OSMType.UNKNOWN);
        manMadeMap.put("cutline", OSMType.CUTLINE);
        manMadeMap.put("dyke", OSMType.DYKE);
        manMadeMap.put("earthwork", OSMType.EARTHWORK);
        manMadeMap.put("ecoduct", OSMType.DYKE);
        manMadeMap.put("embankment", OSMType.EMBANKMENT);
        manMadeMap.put("fence", OSMType.FENCE);
        manMadeMap.put("flagpole", OSMType.UNKNOWN);
        manMadeMap.put("flagpole_row", OSMType.UNKNOWN);
        manMadeMap.put("fuel_tank", OSMType.TANK);
        manMadeMap.put("gasometer", OSMType.TOWER);
        manMadeMap.put("groyne", OSMType.GROYNE);
        manMadeMap.put("guy_wire", OSMType.UNKNOWN);
        manMadeMap.put("hill", OSMType.UNKNOWN);
        manMadeMap.put("hot_water_tank", OSMType.TANK);
        manMadeMap.put("island", OSMType.ISLAND);
        manMadeMap.put("lighthouse", OSMType.TOWER);
        manMadeMap.put("manhole", OSMType.UNKNOWN);
        manMadeMap.put("midden", OSMType.MIDDEN);
        manMadeMap.put("monitoring_station", OSMType.YES_BU);
        manMadeMap.put("monitoring_station;communications_tower", OSMType.YES_BU);
        manMadeMap.put("observatory", OSMType.YES_BU);
        manMadeMap.put("pier", OSMType.PIER);
        manMadeMap.put("pipeline", OSMType.PIPELINE_MA);
        manMadeMap.put("platform", OSMType.PLATFORM);
        manMadeMap.put("pumping station", OSMType.YES_BU);
        manMadeMap.put("pumping_station", OSMType.YES_BU);
        manMadeMap.put("quay", OSMType.QUAY);
        manMadeMap.put("reservoir", OSMType.RESERVOIR);
        manMadeMap.put("reservoir_covered", OSMType.RESERVOIR);
        manMadeMap.put("reservoir_covere", OSMType.RESERVOIR);
        manMadeMap.put("retaining_wall", OSMType.RETAINING_WALL_MA);
        manMadeMap.put("septic_tank", OSMType.TANK);
        manMadeMap.put("silo", OSMType.SILO);
        manMadeMap.put("slurry_tank", OSMType.TANK);
        manMadeMap.put("ston", OSMType.ROCK);
        manMadeMap.put("storage", OSMType.YES_BU);
        manMadeMap.put("storage_tank", OSMType.TANK);
        manMadeMap.put("street_cabinet", OSMType.UNKNOWN);
        manMadeMap.put("submarine_cable", OSMType.UNKNOWN);
        manMadeMap.put("tank", OSMType.TANK);
        manMadeMap.put("telescope", OSMType.YES_BU);
        manMadeMap.put("telephone_exchange", OSMType.YES_BU);
        manMadeMap.put("tolvalenvej", OSMType.RESIDENTIAL_HIG);
        manMadeMap.put("tower", OSMType.TOWER);
        manMadeMap.put("tunnel", OSMType.TUNNEL);
        manMadeMap.put("undefined", OSMType.UNKNOWN);
        manMadeMap.put("wastewater_plant", OSMType.WASTEWATER_PLANT_MA);
        manMadeMap.put("water_tank", OSMType.TANK);
        manMadeMap.put("water_tower", OSMType.TOWER);
        manMadeMap.put("water_well", OSMType.UNKNOWN);
        manMadeMap.put("water_works", OSMType.YES_BU);
        manMadeMap.put("watermill", OSMType.YES_BU);
        manMadeMap.put("wildlife_crossing", OSMType.UNKNOWN);
        manMadeMap.put("windmill", OSMType.WINDMILL_MA);
        manMadeMap.put("works", OSMType.YES_BU);
        manMadeMap.put("wrack", OSMType.WRACK);
        manMadeMap.put("yes", OSMType.YES_MA);
    }

    private void fillMilitaryMap() {
        militaryMap.put("airfield", OSMType.AIRFIELD);
        militaryMap.put("barracks", OSMType.BARRACKS);
        militaryMap.put("bunker", OSMType.BUNKER_MI);
        militaryMap.put("danger_area", OSMType.DANGER_AREA);
        militaryMap.put("naval_academy", OSMType.NAVAL_ACADEMY);
        militaryMap.put("naval_base", OSMType.NAVAL_BASE);
        militaryMap.put("obstacle_course", OSMType.OBSTACLE_COURSE_MI);
        militaryMap.put("office", OSMType.OFFICE_MI);
        militaryMap.put("radar", OSMType.UNKNOWN);
        militaryMap.put("range", OSMType.RANGE);
        militaryMap.put("training_area", OSMType.TRAINING_AREA);
        militaryMap.put("trench", OSMType.TRENCH);
    }

    private void fillNaturalMap() {
        naturalMap.put("bakkehus", OSMType.HOUSE);
        naturalMap.put("bare_rock", OSMType.ROCK);
        naturalMap.put("bay", OSMType.BAY_NA);
        naturalMap.put("beach", OSMType.BEACH);
        naturalMap.put("cape", OSMType.CAPE);
        naturalMap.put("cliff", OSMType.CLIFF);
        naturalMap.put("dune", OSMType.DUNE);
        naturalMap.put("coastline", OSMType.COASTLINE);
        naturalMap.put("earth_bank", OSMType.UNKNOWN);
        naturalMap.put("f", OSMType.UNKNOWN);
        naturalMap.put("fell", OSMType.FELL);
        naturalMap.put("field", OSMType.FIELD);
        naturalMap.put("fjord", OSMType.WATER);
        naturalMap.put("forest", OSMType.FOREST);
        naturalMap.put("grass", OSMType.GRASS_NA);
        naturalMap.put("grassland", OSMType.GRASSLAND);
        naturalMap.put("heath", OSMType.HEATH);
        naturalMap.put("island", OSMType.ISLAND_NA);
        naturalMap.put("meadow", OSMType.MEADOW);
        naturalMap.put("mud", OSMType.MUD);
        naturalMap.put("pasture", OSMType.PASTURE_NA);
        naturalMap.put("peak", OSMType.PEAK);
        naturalMap.put("reef", OSMType.WATER_NA);
        naturalMap.put("ridge", OSMType.RIDGE);
        naturalMap.put("rock", OSMType.ROCK);
        naturalMap.put("sand", OSMType.SAND);
        naturalMap.put("sceub", OSMType.SCRUB);
        naturalMap.put("scree", OSMType.SCREE);
        naturalMap.put("scrub", OSMType.SCRUB);
        naturalMap.put("scrub;wetland", OSMType.SCRUB);
        naturalMap.put("shingle", OSMType.SHINGLE);
        naturalMap.put("shoal", OSMType.SHINGLE);
        naturalMap.put("sloane", OSMType.SLOANE);
        naturalMap.put("spring", OSMType.SPRING);
        naturalMap.put("stone", OSMType.ROCK);
        naturalMap.put("strait", OSMType.UNKNOWN);
        naturalMap.put("thicket", OSMType.THICKET);
        naturalMap.put("tree", OSMType.TREE);
        naturalMap.put("tree_group", OSMType.TREE);
        naturalMap.put("tree_row", OSMType.TREE);
        naturalMap.put("trees", OSMType.TREE);
        naturalMap.put("valley", OSMType.VALLEY);
        naturalMap.put("water", OSMType.WATER_NA);
        naturalMap.put("wetland", OSMType.WETLAND);
        naturalMap.put("wood", OSMType.WOOD);
        naturalMap.put("yes", OSMType.YES_NA);

    }

    private void fillPlaceMap() {
        placeMap.put("allotments", OSMType.ALLOTMENTS_PL);
        placeMap.put("archipelago", OSMType.ARCHIPELAGO);
        placeMap.put("construction", OSMType.UNKNOWN);
        placeMap.put("county", OSMType.UNKNOWN);
        placeMap.put("farm", OSMType.FARM_BU);
        placeMap.put("hamlet", OSMType.HAMLET);
        placeMap.put("island", OSMType.ISLAND);
        placeMap.put("islet", OSMType.ISLET);
        placeMap.put("isolated_dwelling", OSMType.ISOLATED_DWELLING);
        placeMap.put("locality", OSMType.UNKNOWN);
        placeMap.put("municipality", OSMType.UNKNOWN);
        placeMap.put("neighbourhood", OSMType.UNKNOWN);
        placeMap.put("peninsula", OSMType.UNKNOWN);
        placeMap.put("plot", OSMType.UNKNOWN);
        placeMap.put("quarter", OSMType.VILLAGE);
        placeMap.put("sea", OSMType.WATER_NA);
        placeMap.put("square", OSMType.SQUARE);
        placeMap.put("suburb", OSMType.VILLAGE);
        placeMap.put("tobaksholm", OSMType.UNKNOWN);
        placeMap.put("town", OSMType.VILLAGE);
        placeMap.put("village", OSMType.VILLAGE);
    }

    private void fillRailwayMap() {
        railwayMap.put("abandoned", OSMType.UNKNOWN);
        railwayMap.put("construction", OSMType.UNKNOWN);
        railwayMap.put("dismantled", OSMType.UNKNOWN);
        railwayMap.put("disused", OSMType.DISUSED);
        railwayMap.put("ferry", OSMType.UNKNOWN);
        railwayMap.put("fuel", OSMType.UNKNOWN);
        railwayMap.put("light_rail", OSMType.LIGHT_RAIL_RA);
        railwayMap.put("miniature", OSMType.MINIATURE);
        railwayMap.put("monorail", OSMType.MONORAIL);
        railwayMap.put("narrow_gauge", OSMType.UNKNOWN);
        railwayMap.put("platform", OSMType.PLATFORM_RA);
        railwayMap.put("preserved", OSMType.PRESERVED);
        railwayMap.put("proposed", OSMType.UNKNOWN);
        railwayMap.put("rail", OSMType.RAIL);
        railwayMap.put("razed", OSMType.UNKNOWN);
        railwayMap.put("roundhouse", OSMType.YES_BU);
        railwayMap.put("station", OSMType.STATION_RA);
        railwayMap.put("subway", OSMType.SUBWAY);
        railwayMap.put("tram", OSMType.TRAM_RA);
        railwayMap.put("traverser", OSMType.TRAVERSER);
        railwayMap.put("turntable", OSMType.TURNTABLE);
        railwayMap.put("yes", OSMType.YES_RA);
    }

    private void fillWaterwayMap() {
        waterwayMap.put("boatyard", OSMType.UNKNOWN);
        waterwayMap.put("canal", OSMType.CANAL);
        waterwayMap.put("construction", OSMType.UNKNOWN);
        waterwayMap.put("culvert", OSMType.UNKNOWN);
        waterwayMap.put("d", OSMType.UNKNOWN);
        waterwayMap.put("dam", OSMType.DAM);
        waterwayMap.put("dich", OSMType.DITCH_WA);
        waterwayMap.put("ditch", OSMType.DITCH_WA);
        waterwayMap.put("ditch;stream", OSMType.DITCH_WA);
        waterwayMap.put("ditchj", OSMType.DITCH_WA);
        waterwayMap.put("ditvh", OSMType.DITCH_WA);
        waterwayMap.put("dock", OSMType.DOCK);
        waterwayMap.put("drain", OSMType.DRAIN);
        waterwayMap.put("dry_dock", OSMType.DRY_DOCK);
        waterwayMap.put("farms", OSMType.FARMS);
        waterwayMap.put("fish_pass", OSMType.FISH_PASS);
        waterwayMap.put("lock_gate", OSMType.UNKNOWN);
        waterwayMap.put("pond", OSMType.POND_WA);
        waterwayMap.put("proposed", OSMType.UNKNOWN);
        waterwayMap.put("lake", OSMType.LAKE);
        waterwayMap.put("river", OSMType.RIVER);
        waterwayMap.put("riverbank", OSMType.RIVERBANK);
        waterwayMap.put("sitch", OSMType.DITCH_WA);
        waterwayMap.put("str", OSMType.STREAM);
        waterwayMap.put("stream", OSMType.STREAM);
        waterwayMap.put("streamditch", OSMType.STREAM);
        waterwayMap.put("water", OSMType.WATER);
        waterwayMap.put("waterfall", OSMType.WATERFALL);
        waterwayMap.put("weir", OSMType.WEIR);
        waterwayMap.put("yes", OSMType.YES_WA);
    }
}


